ALTER TABLE `User` ADD COLUMN `emailClaims` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `emailMatches` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `emailWeeklyDigest` BOOLEAN NOT NULL DEFAULT true;