[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile=false"]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm build"]

[start]
cmd = "node dist/server.js"